# Generated by Django 4.2.7 on 2023-11-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField()),
                ('description', models.TextField()),
                ('headline', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('main_image', models.CharField(blank=True, default='', max_length=1024)),
                ('tags', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('website_url', models.CharField(blank=True, default='', max_length=1024)),
                ('image_url', models.CharField(blank=True, default='', max_length=1024)),
                ('seatgeek_slug', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'db_table': 'bands',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('band_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('event_id', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(blank=True, default='', max_length=1024)),
                ('city', models.CharField(blank=True, default='', max_length=1024)),
                ('state', models.CharField(blank=True, default='', max_length=1024)),
                ('country', models.CharField(blank=True, default='', max_length=1024)),
                ('image_url', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'db_table': 'shows',
                'ordering': ['id'],
            },
        ),
    ]
