# Generated by Django 4.2.7 on 2023-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('processed', models.BooleanField()),
            ],
            options={
                'db_table': 'article_list',
            },
        ),
    ]
