# Generated by Django 4.2.7 on 2023-12-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0002_articlelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('email', models.CharField(blank=True, default='', max_length=1024)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('send_copy', models.BooleanField()),
                ('answered', models.BooleanField()),
                ('reference', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('email', models.CharField(blank=True, default='', max_length=1024)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('date_unsubscribed', models.DateTimeField()),
                ('date_last_sent', models.DateTimeField()),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
    ]
