# Generated by Django 4.2.7 on 2023-12-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0003_contact_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
