# Generated by Django 4.2.7 on 2023-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0004_alter_contact_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
