# Generated by Django 4.2.3 on 2023-12-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0006_alter_newsletter_date_last_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name']},
        ),
    ]
