# Generated by Django 4.2.3 on 2024-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0007_alter_band_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('band_id', models.IntegerField()),
                ('band_name', models.CharField(blank=True, default='', max_length=1024)),
                ('band_selected', models.BooleanField()),
            ],
            options={
                'db_table': 'userbands',
                'ordering': ['user_id', 'band_id'],
            },
        ),
    ]
