# Generated by Django 4.2.3 on 2023-12-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0007_alter_band_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'feed_sites',
            },
        ),
        migrations.CreateModel(
            name='JambandSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=1024)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'jamband_sites',
            },
        ),
    ]
