# Generated by Django 4.2.3 on 2024-06-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam_site', '0008_feedsites_jambandsites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedSites',
        ),
        migrations.DeleteModel(
            name='JambandSites',
        ),
    ]
